apiVersion: v1
kind: Service
metadata:
  name: goldenpath-runtime
  labels:
    app.kubernetes.io/name: goldenpath-runtime
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: goldenpath-runtime-lab
    app.kubernetes.io/managed-by: argocd
    team: platform
    environment: ephemeral
spec:
  selector:
    app.kubernetes.io/name: goldenpath-runtime
  ports:
    - name: http
      port: 8080
      targetPort: http
