apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payments-staging

resources:
  - ../../base

labels:
  - pairs:
      environment: staging
    includeSelectors: true

images:
  - name: ghcr.io/org/payment-api
    digest: "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"

replicas:
  - name: payment-api
    count: 2

patches:
  - path: resource-patch.yaml
