apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payments-staging

resources:
  - ../../base

commonLabels:
  environment: staging

# Imagen con tag inmutable (SHA o semver, NO latest)
images:
  - name: ghcr.io/org/payment-api
    newTag: "v1.0.0"  # Actualizar via PR de promoción

replicas:
  - name: payment-api
    count: 2

patches:
  - path: resource-patch.yaml
