apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payments-dev

resources:
  - ../../base

labels:
  - pairs:
      environment: dev
    includeSelectors: true

images:
  - name: ghcr.io/org/payment-api
    newTag: "v1.0.0"

patches:
  - path: replica-patch.yaml
