apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/ingress-nginx
  - ../../base/cert-manager
  - ../../base/external-secrets
  - ../../base/prometheus-stack
  - ../../base/loki
  - ../../base/tempo
  - ../../base/gatekeeper

commonLabels:
  environment: staging

patches:
  - target:
      kind: HelmRelease
      name: kube-prometheus-stack
    patch: |
      - op: replace
        path: /spec/values/prometheus/prometheusSpec/retention
        value: 7d
