apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - constraint-templates/k8srequiredlabels.yaml
  - constraint-templates/k8spspprivilegedcontainer.yaml
  - constraint-templates/k8scontainerresources.yaml
  - constraint-templates/k8simmutableimages.yaml
  - constraint-templates/k8ssecurecontext.yaml
  - constraints/required-labels.yaml
  - constraints/no-privileged.yaml
  - constraints/container-limits.yaml
  - constraints/immutable-images.yaml
  - constraints/secure-context.yaml
